# https://github.com/Kampfkarren/selene/issues/284
# std = "lua54+vim"
#
#[rules]
#mixed_table = "allow"
#
std = "vim"

[lints]
mixed_table = "allow"
# one-line closures in plugin specs are idiomatic LazyVim
multiple_statements = "allow"
